Repository trace4cats/trace4cats-exporter-http, pull requests merged in 2021-07, with the labels that each got.

#6 Update Mergify rules
  .github/mergify.yml
Labels: skip-changelog

#9 Update sbt-ci-release-early to 2.0.17
  project/plugins.sbt
Labels: dependency-update

#10 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependency-update

#11 Update sbt to 1.5.5
  project/build.properties
Labels: dependency-update

#12 Add Scala 3 build
  .github/workflows/ci.yml
  ci-release.sbt
  project/Dependencies.scala
Labels: enhancement
